version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: trading-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=trading123!
      - DOCKER_INFLUXDB_INIT_ORG=trading-org
      - DOCKER_INFLUXDB_INIT_BUCKET=trading-signals
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=trading-super-secret-token-12345
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:10.2.0
    container_name: trading-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=trading123!
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - trading-network
    depends_on:
      - influxdb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: trading-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-storage:/data
    networks:
      - trading-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass trading123!
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  trading-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trading-bot
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=trading-super-secret-token-12345
      - INFLUXDB_ORG=trading-org
      - INFLUXDB_BUCKET=trading-signals
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BOT_PORT=8080
      - REDIS_URL=redis://trading123!@redis:6379/0
    volumes:
      - ./logs:/app/logs
    networks:
      - trading-network
    depends_on:
      - influxdb
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  influxdb-storage:
  influxdb-config:
  grafana-storage:
  redis-storage:

networks:
  trading-network:
    driver: bridge